/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/aria2/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aria2 Status
         * @description aria2 是否可用
         *
         *     **不可用不算错误**：服务本身照常跑，这里如实报告状态即可 ——
         *     前端据此显示「aria2 未连接」并给出原因，比整个后端起不来强
         */
        get: operations["aria2_status_api_aria2_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session State
         * @description 查询当前是否已登录。**不需要鉴权** —— 前端要靠它决定跳不跳登录页，
         *     因此只回答「是 / 否」，不带任何其他信息
         */
        get: operations["session_state_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Directory
         * @description 列出一个目录。`path` 为空时给第一个根目录
         */
        get: operations["list_directory_api_files_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/mkdir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make Directory
         * @description 在允许的目录下新建一个子目录
         *
         *     `name` 只能是单个名字，不能是路径：允许它带分隔符的话，`../../x` 就又回来了。
         *     这里既拦名字本身，也仍然让结果过一遍 `resolve_within_roots`
         */
        post: operations["make_directory_api_files_mkdir_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Roots
         * @description 可浏览的根目录。前端据此显示入口，不给用户输入任意路径的机会
         */
        get: operations["list_roots_api_files_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查。**不需要登录** —— 反向代理与容器编排要靠它判断存活，
         *     因此这里也不能泄漏任何有意义的信息
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login With Cookie
         * @description 用粘贴的 Cookie 登录。验证不通过会回滚，不会把无效 Cookie 留在 client 上
         */
        post: operations["login_with_cookie_api_login_cookie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description 退出 B 站账号。**不影响 WebUI 自身的会话**
         */
        post: operations["logout_api_login_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/qrcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Qrcode
         * @description 申请一个登录二维码
         *
         *     返回的 `url` 由前端渲染成二维码，`key` 用于后续轮询
         */
        post: operations["create_qrcode_api_login_qrcode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/qrcode/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll Qrcode
         * @description 查一次扫码状态
         *
         *     状态为 `success` 时 Cookie 已经写进配置了（在 `parse_poll` 里就地完成），
         *     前端接着调 `/api/login/status?refresh=true` 取用户信息即可
         */
        get: operations["poll_qrcode_api_login_qrcode_poll_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/sms/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sms Captcha
         * @description 申请极验参数
         *
         *     前端拿 `gt` 与 `challenge` 调 `initGeetest`（写法见 `src/res/html/captcha.html`），
         *     `token` 原样留着，发短信时要带回去
         */
        post: operations["sms_captcha_api_login_sms_captcha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/sms/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sms Regions
         * @description 国家/地区区号。与桌面版下拉框用的是同一份数据
         */
        get: operations["sms_regions_api_login_sms_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/sms/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sms Send
         * @description 发送验证码短信。返回的 captcha_key 登录时要用
         */
        post: operations["sms_send_api_login_sms_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/sms/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sms Verify
         * @description 用收到的验证码完成登录
         */
        post: operations["sms_verify_api_login_sms_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login Status
         * @description 当前的 B 站登录态
         *
         *     `refresh = True` 时去问一次 nav 接口（顺带刷新 wbi 签名用的 key）；
         *     否则只报配置里存的状态，不发请求 —— 前端轮询这个接口时不该每次都打一次 B 站
         */
        get: operations["login_status_api_login_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Url
         * @description 解析一个链接，返回剧集树
         *
         *     树的叶子节点带 `episode` 字段 —— 那正是创建下载任务时要交回来的东西，
         *     前端原样回传即可，不必自己拼
         */
        post: operations["parse_url_api_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Episodes
         * @description 从解析树里把叶子摘出来
         *
         *     前端完全可以自己遍历，这里提供一份是为了**让摘取规则只有一处**：
         *     树节点（`is_node`）不算下载项，这条规则改了两边就会对不上
         */
        post: operations["extract_episodes_api_parse_episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read History */
        get: operations["read_history_api_parse_history_get"];
        put?: never;
        post?: never;
        /** Clear History */
        delete: operations["clear_history_api_parse_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/history/{history_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete History */
        delete: operations["delete_history_api_parse_history__history_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description 取一次媒体信息，返回可选的画质 / 编码 / 音质
         */
        post: operations["preview_api_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Settings
         * @description 读配置
         *
         *     附带每一项的类型、默认值、取值范围与可选值 —— 前端据此把设置界面画出来，
         *     不必自己维护一份与 schema 平行的表（那份表迟早对不上）
         */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        /**
         * Update Settings
         * @description 改配置
         *
         *     一次可以改多项。认不出的 attr 与敏感项**直接拒绝整个请求**，不做「部分成功」——
         *     改配置是用户在设置界面点保存，半对半错的结果比明确报错更难收拾
         */
        post: operations["update_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Choices
         * @description 结构化配置项的候选值：画质 / 音质 / 编码 / 字幕语言
         *
         *     **这些表只有 core 里那一份。** 前端再抄一遍的话，B 站加一档新画质时桌面版认得、
         *     WebUI 不认得，而且没有任何报错 —— 只是那一档在优先级列表里凭空消失。
         *
         *     画质与音质里的 `auto` 不下发：优先级列表本身回答的就是「auto 时按什么顺序挑」，
         *     把 auto 放进这个顺序里没有意义（配置的默认值里也没有它）
         */
        get: operations["read_choices_api_settings_choices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Fonts
         * @description 服务端装了哪些字体
         *
         *     **这里会惰性拉起 offscreen 的 QGuiApplication**（`web/qt_runtime.py`），
         *     与生成 ASS 弹幕走的是同一条路 —— 也正因如此，列出来的就是那时真正能用的字体。
         *
         *     必须在事件循环线程（= 主线程）上调用：QGuiApplication 只能在主线程构造。
         *     所以这个函数是 async 且**不能**丢给 `run_in_executor`。
         *
         *     ## 空列表是常态，不是错误
         *
         *     实测：**Windows 上 `QT_QPA_PLATFORM=offscreen` 一款字体都枚举不到**
         *     （`QFontDatabase.families()` 返回空，systemFont 是 "Sans Serif"）。
         *     Linux 容器里走 fontconfig 通常能列出来，但也取决于镜像里装没装字体。
         *
         *     所以 `available` 的含义是「**这份列表能用吗**」，不是「Qt 在不在」——
         *     列表为空时前端会退回自由输入框，让用户自己填字体名。
         *     报 available 却给一个空列表，比直接说不可用更糟：前端会画出一个点不开的空下拉框。
         *
         *     顺带一提：枚举不到字体也就意味着 ASS 弹幕的轨道排布是按 fallback 字体量的，
         *     宽度会有偏差。那属于 D16 已经接受的近似（见 PROGRESS 的待解决第 4 条）
         */
        get: operations["read_fonts_api_settings_fonts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/naming-rule/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Naming Rule
         * @description 校验一条规则并套上示例数据
         *
         *     **非法的规则也返回 200**：这里回答的是「这条规则行不行」，
         *     不合法是一个正常的答案，不是请求出错。用 4xx 的话前端得把「校验没通过」
         *     和「请求本身失败」分开处理，而它们在界面上是两回事
         */
        post: operations["preview_naming_rule_api_settings_naming_rule_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/naming-rule/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Naming Rule Types
         * @description 规则类型。名字与编号都由 core 给，前端不自己维护一份对照表
         */
        get: operations["read_naming_rule_types_api_settings_naming_rule_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/naming-rule/variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Naming Rule Variables
         * @description 某个规则类型能用哪些变量。认不出的类型返回空表而不是报错
         */
        get: operations["read_naming_rule_variables_api_settings_naming_rule_variables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description 登录后可见的运行状态
         */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Task Snapshot
         * @description 全量快照
         *
         *     带上 `cursor`：前端拿它去连 WebSocket（`?since=cursor`），服务端会把这之后的
         *     增量补发出来。没有这个游标的话，快照与增量之间会漏掉一段
         */
        get: operations["task_snapshot_api_tasks_get"];
        put?: never;
        /**
         * Create Tasks
         * @description 创建下载任务
         *
         *     `task_manager.create()` 内部会做**重复下载判定**与**是否需要二次解析**的判断，
         *     所以实际建出来的可能比传进来的少 —— 返回里如实给出两个数字，
         *     不然前端会以为「点了没反应」
         */
        post: operations["create_tasks_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count Tasks */
        get: operations["count_tasks_api_tasks_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Tasks
         * @description 删除任务
         *
         *     **同时删掉临时文件**（`cancel_many_async` 负责）。只删记录的话，
         *     下载目录里会留下一堆 `video_<task_id>.m4s`，而且再也没人认得它们属于谁
         */
        post: operations["delete_tasks_api_tasks_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Duplicates
         * @description 这批条目里哪些已经下载过
         *
         *     只查不改，也**不触发任何界面交互** —— `task_manager.is_duplicate` 那条路径本身就是
         *     为无人值守的调用方准备的。
         *
         *     解析页靠它把已下过的标出来。那不是锦上添花：重复项在服务端是被**静默跳过**的
         *     （WebUI 没有可询问的对象），不提前标的话，用户点完下载只会看到
         *     「创建了 3 个，共勾选 10 项」，而不知道另外 7 项去了哪里
         */
        post: operations["check_duplicates_api_tasks_duplicates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description 列出任务，可排序
         *
         *     与 `GET /api/tasks` 的区别：那个是给「刷新页面恢复现场」用的全量快照（带事件游标），
         *     这个是给列表视图用的，可以排序与限量
         */
        get: operations["list_tasks_api_tasks_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Tasks
         * @description 暂停：让 aria2 停下来，并把任务状态置为已暂停
         */
        post: operations["pause_tasks_api_tasks_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Tasks
         * @description 恢复
         */
        post: operations["resume_tasks_api_tasks_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Tasks
         * @description 重新下载
         *
         *     先 `reset` 把进度与分片记录清干净再 `recreate` —— 只改状态不清记录的话，
         *     续传会接着上一次那份已经作废的分片表走
         */
        post: operations["retry_tasks_api_tasks_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Update
         * @description 问一次版本服务有没有新版本
         *
         *     **不做缓存也不自动轮询**：调用点只有标题栏那个按钮和进入页面时的一次，
         *     加一层缓存反而会让「点了没反应」变得难查。
         *
         *     `include_preview` 不传就用共用配置里的 `include_prerelease`，与桌面版一致
         */
        get: operations["check_update_api_update_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Aria2Status
         * @description aria2 不可用不算错误，如实报告即可
         */
        Aria2Status: {
            /**
             * Active
             * @default 0
             */
            active: number;
            /** Connected */
            connected: boolean;
            /**
             * Download Speed
             * @default 0
             */
            download_speed: number;
            /** Error */
            error?: string | null;
            /**
             * Stopped
             * @default 0
             */
            stopped: number;
            /** Version */
            version?: string | null;
            /**
             * Waiting
             * @default 0
             */
            waiting: number;
        };
        /** BilibiliStatus */
        BilibiliStatus: {
            /**
             * Expired
             * @default false
             */
            expired: boolean;
            /**
             * Face
             * @default
             */
            face: string;
            /**
             * Level
             * @default 0
             */
            level: number;
            /** Logged In */
            logged_in: boolean;
            /**
             * Uid
             * @default 0
             */
            uid: number | string;
            /**
             * Uname
             * @default
             */
            uname: string;
            /**
             * Vip Status
             * @default 0
             */
            vip_status: number;
        };
        /**
         * CaptchaInfo
         * @description 极验参数。前端拿 gt / challenge 调 initGeetest，token 发短信时带回来
         */
        CaptchaInfo: {
            /** Challenge */
            challenge: string;
            /** Gt */
            gt: string;
            /** Token */
            token: string;
        };
        /** CheckDuplicatesRequest */
        CheckDuplicatesRequest: {
            /** Episodes */
            episodes: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Choice
         * @description 一个可选项。value 的类型随配置项而变（画质是 int，字幕语言是字符串）
         */
        Choice: {
            /** Label */
            label: string;
            /** Value */
            value: unknown;
        };
        /** CookieLoginRequest */
        CookieLoginRequest: {
            /** Text */
            text: string;
        };
        /**
         * CreateResult
         * @description 实际建出来的可能比请求的少：重复下载与需要二次解析的会被拦掉
         */
        CreateResult: {
            /** Created */
            created: number;
            /** Requested */
            requested: number;
            /** Tasks */
            tasks: components["schemas"]["TaskView"][];
        };
        /** CreateTasksRequest */
        CreateTasksRequest: {
            /** Episodes */
            episodes: {
                [key: string]: unknown;
            }[];
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
        };
        /** DeleteResult */
        DeleteResult: {
            /** Deleted */
            deleted: number;
        };
        /** DirectoryListing */
        DirectoryListing: {
            /** Entries */
            entries: components["schemas"]["FileEntry"][];
            /** Parent */
            parent?: string | null;
            /** Path */
            path: string;
            /** Relative */
            relative?: string | null;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * DuplicateCheck
         * @description 每一条是否已经下载过，**与请求里的 episodes 一一对应、顺序一致**
         *
         *     不用「已重复的下标列表」是因为那要求两边对「下标从哪算」有一致理解，
         *     而等长的布尔列表没有这个歧义
         */
        DuplicateCheck: {
            /** Duplicates */
            duplicates: boolean[];
        };
        /**
         * EpisodeList
         * @description `episode` 是 TaskInfo 那套自由字典，原样回传给创建任务的接口即可
         */
        EpisodeList: {
            /** Episodes */
            episodes: {
                [key: string]: unknown;
            }[];
        };
        /** FileEntry */
        FileEntry: {
            /** Is Dir */
            is_dir: boolean;
            /** Is Link */
            is_link: boolean;
            /** Modified */
            modified: number;
            /** Name */
            name: string;
            /** Size */
            size: number;
        };
        /** FileRoot */
        FileRoot: {
            /** Exists */
            exists: boolean;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** FileRoots */
        FileRoots: {
            /** Roots */
            roots: components["schemas"]["FileRoot"][];
        };
        /**
         * FontFamilies
         * @description 服务端装了哪些字体
         *
         *     **要的是服务端的字体，不是浏览器所在机器的。** ASS 是在服务端生成的，
         *     弹幕轨道的排布还要靠 QFontMetrics 量文字宽度（见 `web/qt_runtime.py`），
         *     填一个服务端没有的字体名，度量会落到 fallback 字体上，排出来的轨道会偏。
         *
         *     取不到时 `available` 为假（镜像里没装 PySide6 就是这样），
         *     前端据此退回成一个自由输入框 —— 那时用户得自己保证名字对
         */
        FontFamilies: {
            /** Available */
            available: boolean;
            /** Families */
            families: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthInfo */
        HealthInfo: {
            /** Status */
            status: string;
        };
        /** HistoryDeleteResult */
        HistoryDeleteResult: {
            /** Deleted */
            deleted: number;
        };
        /**
         * HistoryEntry
         * @description 一条解析历史。字段名与 `util/misc/history.py` 建的表一一对应
         */
        HistoryEntry: {
            /** Created Time */
            created_time: number;
            /** History Id */
            history_id: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Url */
            url: string;
        };
        /** HistoryList */
        HistoryList: {
            /** Entries */
            entries: components["schemas"]["HistoryEntry"][];
            /** Max Length */
            max_length: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LogoutResult */
        LogoutResult: {
            /**
             * Authenticated
             * @default false
             */
            authenticated: boolean;
        };
        /** MakeDirResult */
        MakeDirResult: {
            /** Path */
            path: string;
            /** Relative */
            relative?: string | null;
        };
        /** MkdirRequest */
        MkdirRequest: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /**
         * NamingRulePreview
         * @description 校验结果与套上示例数据之后的样子
         *
         *     判据在 `util/format/naming_rule.py`，桌面版的编辑对话框用的是同一份 ——
         *     两边各写一套的话，迟早出现「桌面版存得下的规则 WebUI 说非法」
         */
        NamingRulePreview: {
            /** Filename */
            filename?: string | null;
            /** Folder */
            folder?: string | null;
            /** Message */
            message?: string | null;
            /** Valid */
            valid: boolean;
        };
        /** NamingRulePreviewRequest */
        NamingRulePreviewRequest: {
            /** Rule */
            rule: string;
            /** Type */
            type: number;
        };
        /**
         * NamingRuleTypes
         * @description 规则类型（单个视频 / 多 P / 合集 …）与各自可用的变量
         */
        NamingRuleTypes: {
            /** Types */
            types: components["schemas"]["Choice"][];
        };
        /** NamingRuleVariables */
        NamingRuleVariables: {
            /** Variables */
            variables: components["schemas"]["NamingVariable"][];
        };
        /** NamingVariable */
        NamingVariable: {
            /** Description */
            description: string;
            /** Example */
            example: string;
            /** Variable */
            variable: string;
        };
        /** ParseRequest */
        ParseRequest: {
            /** Keyword */
            keyword?: string | null;
            /**
             * Pn
             * @default 1
             */
            pn: number;
            /** Url */
            url: string;
        };
        /** PauseResult */
        PauseResult: {
            /** Status */
            status: string;
            /** Streams Affected */
            streams_affected: number;
            /** Updated */
            updated: number;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Candidates */
            candidates: {
                [key: string]: unknown;
            }[];
        };
        /** PreviewResult */
        PreviewResult: {
            /** Audio Quality */
            audio_quality?: {
                [key: string]: number;
            };
            /**
             * Bvid
             * @default
             */
            bvid: string;
            /**
             * Cid
             * @default 0
             */
            cid: number;
            /**
             * Episode Number
             * @default
             */
            episode_number: string | number;
            /**
             * Episode Title
             * @default
             */
            episode_title: string;
            /**
             * From Fallback
             * @default false
             */
            from_fallback: boolean;
            /**
             * Media Type
             * @default unknown
             */
            media_type: string;
            /**
             * Need Parse
             * @default true
             */
            need_parse: boolean;
            /** Video Codec */
            video_codec?: {
                [key: string]: number;
            };
            /** Video Quality */
            video_quality?: {
                [key: string]: number;
            };
        };
        /**
         * QRCodeInfo
         * @description `url` 交给前端渲染成二维码，服务端不出图
         */
        QRCodeInfo: {
            /** Key */
            key: string;
            /** Url */
            url: string;
        };
        /** QRCodeStatus */
        QRCodeStatus: {
            /** Code */
            code: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Status */
            status: string;
        };
        /** Region */
        Region: {
            /** Code */
            code: string | number;
        } & {
            [key: string]: unknown;
        };
        /** RegionList */
        RegionList: {
            /** Regions */
            regions: components["schemas"]["Region"][];
        };
        /** RetryResult */
        RetryResult: {
            /** Retried */
            retried: number;
        };
        /** SMSSendRequest */
        SMSSendRequest: {
            /** Challenge */
            challenge: string;
            /** Cid */
            cid: string;
            /** Seccode */
            seccode: string;
            /** Tel */
            tel: string;
            /** Token */
            token: string;
            /** Validate */
            validate: string;
        };
        /**
         * SMSSendResult
         * @description captcha_key 是**发短信的返回值**，登录时才用，别与极验的三件套搞混
         */
        SMSSendResult: {
            /** Captcha Key */
            captcha_key: string;
        };
        /** SMSVerifyRequest */
        SMSVerifyRequest: {
            /** Captcha Key */
            captcha_key: string;
            /** Cid */
            cid: string;
            /** Code */
            code: string;
            /** Tel */
            tel: string;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Authenticated */
            authenticated: boolean;
            /**
             * Username
             * @default
             */
            username: string;
        };
        /**
         * SettingChoices
         * @description 结构化配置项的候选值
         *
         *     这些表长在 core 里（`util/common/data/media_info.py` 等），**不该在前端再抄一份**：
         *     抄了之后 B 站加一档新画质，桌面版认得而 WebUI 不认得，且没有任何报错。
         *     与 `/api/preview` 下发画质档位是同一个思路。
         */
        SettingChoices: {
            /** Audio Quality */
            audio_quality: components["schemas"]["Choice"][];
            /** Subtitle Alignment */
            subtitle_alignment: components["schemas"]["Choice"][];
            /** Subtitle Language */
            subtitle_language: components["schemas"]["Choice"][];
            /** Video Codec */
            video_codec: components["schemas"]["Choice"][];
            /** Video Quality */
            video_quality: components["schemas"]["Choice"][];
        };
        /** SettingItem */
        SettingItem: {
            /** Attr */
            attr: string;
            /** Default */
            default?: unknown;
            /** Group */
            group: string;
            /** Options */
            options?: unknown[] | null;
            /** Range */
            range?: unknown[] | null;
            /**
             * Restart
             * @default false
             */
            restart: boolean;
            /** Type */
            type: string;
            /** Value */
            value?: unknown;
        };
        /** SettingsPayload */
        SettingsPayload: {
            /** Groups */
            groups: string[];
            /** Items */
            items: components["schemas"]["SettingItem"][];
        };
        /** SettingsUpdateResult */
        SettingsUpdateResult: {
            /** Changed */
            changed: string[];
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** SystemStatus */
        SystemStatus: {
            /** Logged In Bilibili */
            logged_in_bilibili: boolean;
            /**
             * Uid
             * @default
             */
            uid: number | string;
            /**
             * Uname
             * @default
             */
            uname: string;
            /** Version */
            version: string;
        };
        /** TaskCount */
        TaskCount: {
            /** Completed */
            completed: number;
            /** Downloading */
            downloading: number;
        };
        /** TaskIdsRequest */
        TaskIdsRequest: {
            /** Task Ids */
            task_ids: string[];
        };
        /** TaskList */
        TaskList: {
            /** Ascending */
            ascending: boolean;
            /** Sort By */
            sort_by: string;
            /** Tasks */
            tasks: components["schemas"]["TaskView"][];
        };
        /**
         * TaskSnapshot
         * @description 全量快照
         *
         *     `cursor` 是发快照那一刻的事件编号，前端带着它连 WebSocket（`?since=cursor`），
         *     否则快照与增量之间会漏掉一段
         */
        TaskSnapshot: {
            /** Completed */
            completed: components["schemas"]["TaskView"][];
            /** Cursor */
            cursor: number;
            /** Downloading */
            downloading: components["schemas"]["TaskView"][];
        };
        /**
         * TaskView
         * @description 与 `web/download/view.py` 的 `task_view()` 一一对应
         *
         *     **两边字段必须同步**：那边加了字段这里不加，前端就看不见；
         *     这里多写一个那边没有的，前端会拿到 undefined
         */
        TaskView: {
            /**
             * Audio Quality
             * @default
             */
            audio_quality: string;
            /**
             * Completed Time
             * @default 0
             */
            completed_time: number;
            /**
             * Cover Id
             * @default
             */
            cover_id: string;
            /**
             * Created Time
             * @default 0
             */
            created_time: number;
            /**
             * Download Path
             * @default
             */
            download_path: string;
            /**
             * Downloaded Size
             * @default 0
             */
            downloaded_size: number;
            /**
             * Duration
             * @default 0
             */
            duration: number;
            /**
             * File Name
             * @default
             */
            file_name: string;
            /**
             * Folder
             * @default
             */
            folder: string;
            /**
             * Info Label
             * @default
             */
            info_label: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Speed
             * @default 0
             */
            speed: number;
            /** Status */
            status: string;
            /**
             * Status Label
             * @default
             */
            status_label: string;
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /**
             * Total Size
             * @default 0
             */
            total_size: number;
            /** Type */
            type?: string[];
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Video Codec
             * @default
             */
            video_codec: string;
            /**
             * Video Quality
             * @default
             */
            video_quality: string;
        };
        /**
         * UpdateInfo
         * @description 检查更新的结果
         *
         *     `checked` 为 false 表示这次没问成（网络不通、服务端出错），`error` 里是原因。
         *     **不要用 `should_update` 兼作「问没问到」** —— 那样一次失败会被当成「已是最新」
         */
        UpdateInfo: {
            /**
             * Checked
             * @default false
             */
            checked: boolean;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Current Version
             * @default
             */
            current_version: string;
            /**
             * Error
             * @default
             */
            error: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Should Update
             * @default false
             */
            should_update: boolean;
            /**
             * Update Url
             * @default
             */
            update_url: string;
            /**
             * Version
             * @default
             */
            version: string;
        };
        /** UpdateSettingsRequest */
        UpdateSettingsRequest: {
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    aria2_status_api_aria2_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aria2Status"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResult"];
                };
            };
        };
    };
    session_state_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    list_directory_api_files_list_get: {
        parameters: {
            query?: {
                path?: string;
                dirs_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    make_directory_api_files_mkdir_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MkdirRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MakeDirResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roots_api_files_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRoots"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthInfo"];
                };
            };
        };
    };
    login_with_cookie_api_login_cookie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookieLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BilibiliStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_login_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BilibiliStatus"];
                };
            };
        };
    };
    create_qrcode_api_login_qrcode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRCodeInfo"];
                };
            };
        };
    };
    poll_qrcode_api_login_qrcode_poll_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRCodeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sms_captcha_api_login_sms_captcha_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaInfo"];
                };
            };
        };
    };
    sms_regions_api_login_sms_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionList"];
                };
            };
        };
    };
    sms_send_api_login_sms_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMSSendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMSSendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sms_verify_api_login_sms_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMSVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BilibiliStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_status_api_login_status_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BilibiliStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_url_api_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_episodes_api_parse_episodes_post: {
        parameters: {
            query?: {
                only_checked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_history_api_parse_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryList"];
                };
            };
        };
    };
    clear_history_api_parse_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDeleteResult"];
                };
            };
        };
    };
    delete_history_api_parse_history__history_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                history_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsPayload"];
                };
            };
        };
    };
    update_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_choices_api_settings_choices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingChoices"];
                };
            };
        };
    };
    read_fonts_api_settings_fonts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontFamilies"];
                };
            };
        };
    };
    preview_naming_rule_api_settings_naming_rule_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamingRulePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamingRulePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_naming_rule_types_api_settings_naming_rule_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamingRuleTypes"];
                };
            };
        };
    };
    read_naming_rule_variables_api_settings_naming_rule_variables_get: {
        parameters: {
            query: {
                type: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamingRuleVariables"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    task_snapshot_api_tasks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tasks_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTasksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_tasks_api_tasks_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCount"];
                };
            };
        };
    };
    delete_tasks_api_tasks_delete_post: {
        parameters: {
            query?: {
                completed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_duplicates_api_tasks_duplicates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDuplicatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_list_get: {
        parameters: {
            query?: {
                completed?: boolean;
                sort_by?: string;
                ascending?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_tasks_api_tasks_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_tasks_api_tasks_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_tasks_api_tasks_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIdsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_update_api_update_get: {
        parameters: {
            query?: {
                include_preview?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
