
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""从 Firefox 浏览器提取 cookies 并保存到 cookies.txt"""

import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from yt_dlp.cookies import extract_cookies_from_browser

cookie_file = os.path.join(os.path.dirname(__file__), 'cookies.txt')

print("正在从 Firefox 浏览器提取 YouTube cookies...")
print()

try:
    cookies = extract_cookies_from_browser('firefox')
    
    youtube_cookies = []
    for cookie in cookies:
        if 'youtube.com' in cookie.domain or '.youtube.com' == cookie.domain:
            youtube_cookies.append(cookie)
    
    print(f"找到 {len(youtube_cookies)} 个 YouTube cookies")
    print()
    
    with open(cookie_file, 'w', encoding='utf-8') as f:
        f.write('# Netscape HTTP Cookie File\n')
        f.write('# This file is generated by yt-dlp.  Do not edit.\n')
        f.write('\n')
        
        for cookie in youtube_cookies:
            domain = cookie.domain
            flag = 'TRUE' if cookie.domain.startswith('.') else 'FALSE'
            path = cookie.path
            secure = 'TRUE' if cookie.secure else 'FALSE'
            expiration = str(int(cookie.expires)) if cookie.expires else '0'
            name = cookie.name
            value = cookie.value
            
            f.write(f'{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n')
    
    print(f"Cookies 已保存到: {cookie_file}")
    print(f"文件大小: {os.path.getsize(cookie_file)} 字节")
    print(f"Cookie 数量: {len(youtube_cookies)}")
    
    cookie_names = [c.name for c in youtube_cookies[:10]]
    print(f"\nCookies 列表 (前10个): {', '.join(cookie_names)}")
    
    print("\n=== 提取完成 ===")
    
except Exception as e:
    print(f"\n错误: {e}")
    import traceback
    traceback.print_exc()
