from utils.common.data_type import ASSDialogueData

class ASS:
    @classmethod
    def make(cls, dialogue_list: list):
        sections = (cls.get_script_info(), cls.get_styles(), cls.get_events(dialogue_list))

        return "\n\n".join(sections)

    @classmethod
    def get_script_info(cls):
        data = [
            (";", "Script generated by Bili23 Downloader"),
            (";", "https://bili23.scott-sloan.cn"),
            ("PlayResX", 1920),
            ("PlayRexY", 1080),
            ("ScriptType", "v4.00+")
        ]

        return cls.format_section("Script Info", data)
    
    @classmethod
    def get_styles(cls):
        data = [
            ("Format", "Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"),
            ("Style", "Default,微软雅黑,52,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,30,1")
        ]

        return cls.format_section("V4+ Styles", data)

    @classmethod
    def get_events(cls, dialogue_list: list):
        def get_dialogue_data(start: str, end: str, text: str):
            data = ASSDialogueData()

            data.Start = start
            data.End = end
            data.Text = text

            return data.to_string()

        data = [
            ("Format", "Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"),
        ]

        dialogues = [("Dialogue", get_dialogue_data(start, end, text)) for (start, end, text) in dialogue_list]

        data.extend(dialogues)
        
        return cls.format_section("Events", data)
    
    @staticmethod
    def format_section(title: str, data: list):
        return f"[{title}]\n" + "\n".join([f"{key}: {value}" if key != ";" else f"; {value}" for (key, value) in data])