from gui.dialog.setting.subtitles_language import SubtitlesLanguageDialog
from gui.dialog.setting.speed_limit_rate import SpeedLimitSettingDialog
from gui.dialog.setting.parse_list_column import ParseListColumnDialog
from gui.dialog.setting.subtitles_style import SubtitlesStyleDialog
from gui.dialog.setting.starting_number import StartingNumberDialog
from gui.dialog.setting.danmaku_style import DanmakuStyleDialog
from gui.dialog.setting.cdn_server import CDNServerDialog
from gui.dialog.setting.user_agent import UserAgentDialog
from gui.dialog.setting.edit_rule import EditRuleDialog
from gui.dialog.setting.rule_list import RuleListDialog
from gui.dialog.setting.priority import PriorityDialog
from gui.dialog.setting.proxy import ProxyDialog
