from .subtitles_language import SubtitlesLanguageDialog
from .speed_limit import SpeedLimitSettingDialog
from .parse_list import ParseListSettingsDialog
from .subtitles_style import SubtitlesStyleDialog
from .starting_number import StartingNumberDialog
from .danmaku_style import DanmakuStyleDialog
from .cdn_server import CDNServerDialog
from .user_agent import UserAgentDialog
from .edit_rule import EditRuleDialog
from .rule_list import RuleListDialog
from .priority import PriorityDialog
from .proxy import ProxyDialog
