from .watch_later import WatchLaterParser
from .favorite import FavoriteParser
from .festival import FestivalParser
from .bangumi import BangumiParser
from .popular import PopularParser
from .favlist import FavlistParser
from .history import HistoryParser
from .cheese import CheeseParser
from .video import VideoParser
from .space import SpaceParser
from .list import ListParser
from .b23 import B23Parser